# Generated by Django 5.1.7 on 2025-05-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_approval_status_and_more'),
    ]

    operations = [
    ]
