# Generated by Django 5.1.7 on 2025-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voucher_reference',
            field=models.CharField(blank=True, help_text='Optional voucher code or reference number (letters and numbers allowed)', max_length=50, null=True),
        ),
    ]
