# Generated by Django 5.1.7 on 2025-06-13 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogress',
            old_name='created_at',
            new_name='first_practiced',
        ),
        migrations.RemoveField(
            model_name='practiceresponse',
            name='viewed_explanation',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='easy_attempted',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='easy_correct',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='hard_attempted',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='hard_correct',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='medium_attempted',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='medium_correct',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='total_time_spent',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='time_per_question',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='timed_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='average_accuracy',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='mastery_level',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Getting Started', 'Getting Started'), ('Needs Practice', 'Needs Practice'), ('Fair', 'Fair'), ('Good', 'Good'), ('Mastered', 'Mastered')], default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='degree',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='difficulty_filter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='total_questions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='year',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='best_accuracy',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='degree',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='year',
            field=models.CharField(max_length=3),
        ),
    ]
