# Generated by Django 5.1.7 on 2025-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemodule', '0002_rename_created_at_studentprogress_first_practiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='practice_mode',
            field=models.CharField(choices=[('student', 'Student Mode'), ('tutor', 'Tutor Mode')], default='student', max_length=10),
        ),
    ]
