# Generated by Django 5.1.7 on 2025-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemodule', '0003_practicesession_practice_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceresponse',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
