# Generated by Django 5.1.7 on 2025-06-09 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('degree', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BDS', 'BDS')], max_length=4)),
                ('year', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=3)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=50)),
                ('passing_percentage', models.IntegerField(default=40)),
                ('max_attempts', models.IntegerField(default=1)),
                ('selection_type', models.CharField(choices=[('random', 'Random Selection'), ('manual', 'Manual Selection')], default='random', max_length=10)),
                ('easy_percentage', models.IntegerField(default=30)),
                ('medium_percentage', models.IntegerField(default=50)),
                ('hard_percentage', models.IntegerField(default=20)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('show_explanations', models.BooleanField(default=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('warning_count', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocktest.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('student', 'mock_test', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=1)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.question')),
            ],
            options={
                'ordering': ['question_order'],
                'unique_together': {('mock_test', 'question')},
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(through='mocktest.TestQuestion', to='questionbank.question'),
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mocktest.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
