# Generated by Django 5.1.7 on 2025-06-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('selected_paper_name', models.CharField(max_length=200)),
                ('filter_degree', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BDS', 'BDS')], max_length=4)),
                ('filter_year', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=3)),
                ('filter_module', models.CharField(blank=True, max_length=100)),
                ('filter_subject', models.CharField(blank=True, max_length=100)),
                ('filter_topic', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=0)),
                ('passing_percentage', models.IntegerField(default=40)),
                ('max_attempts', models.IntegerField(default=1)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('show_explanations', models.BooleanField(default=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPaperAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('warning_count', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0)),
                ('model_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='modelpaper.modelpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('student', 'model_paper', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='PaperCSVImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing')], default='PROCESSING', max_length=10)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('paper_names_imported', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper CSV Import History',
                'verbose_name_plural': 'Paper CSV Import Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('option_e', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('paper_name', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BDS', 'BDS')], max_length=4)),
                ('year', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=3)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=6)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paper_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelPaperResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='modelpaper.modelpaperattempt')),
                ('paper_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelpaper.paperquestion')),
            ],
            options={
                'unique_together': {('attempt', 'paper_question')},
            },
        ),
    ]
