# Generated by Django 5.1.7 on 2025-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperquestion',
            name='image',
            field=models.CharField(blank=True, help_text='Image filename (e.g., heart_anatomy.jpg)', max_length=255, null=True),
        ),
    ]
