# Generated by Django 5.1.7 on 2025-06-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelpaper', '0002_paperquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpaperresponse',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
