# Generated by Django 5.1.7 on 2025-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelpaper', '0003_modelpaperresponse_answered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperquestion',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
