# Generated by Django 5.1.7 on 2025-06-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelpaper', '0004_alter_paperquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperquestion',
            name='image',
        ),
    ]
