# Generated by Django 5.1.7 on 2025-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelpaper', '0005_remove_paperquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperquestion',
            name='image',
            field=models.CharField(blank=True, help_text='Image to display with explanation (filename only)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='paper_image',
            field=models.CharField(blank=True, help_text='Image to display with the question (filename only)', max_length=255, null=True),
        ),
    ]
