# Generated by Django 5.1.7 on 2025-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.CharField(blank=True, help_text='Image to display with the question (filename only)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, help_text='Image to display with explanation (filename only)', max_length=255, null=True),
        ),
    ]
