# Generated by Django 5.1.7 on 2025-04-25 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_alter_question_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='question',
            name='block',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='degree',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS')], default='MBBS', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], default='1st', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SEQ', 'Short Essay Question'), ('NOTE', 'Notes')], default='MCQ', max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
