# Generated by Django 5.1.7 on 2025-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0005_alter_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
    ]
